name: Create Release

on: 
  push:
    branches:
      - release

jobs:
  release-on-push:
    
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - id: release
      - uses: rymndhng/release-on-push-action@v0.25.0
        with:
          bump_version_scheme: minor
          tag_prefix: v
    - name: Check Output Parameters
      run: |
        echo "Tag name ${{ steps.release.outputs.tag_name }}"
        echo "Release version ${{ steps.release.outputs.version }}"